version: 2

seeds:
  - name: MDM_INFO_METADATA
    config:
      column_types:
        PROJECT_NAME: VARCHAR2(255)
        PRODUCT_NAME: VARCHAR2(255)
        SOURCE_SYSTEM: VARCHAR2(255)
        COLUMN_ORD: INT
        COLUMN_NAME: VARCHAR2(255)
        COLUMN_TYPE: VARCHAR2(255)
        IS_PK: INT
        IS_COB_DATE: INT
        IS_MASTER_KEY: INT
        HAS_CDT: INT
        DESCRIPTION: VARCHAR2(255)

  - name: MDM_INFO_RUN
    config:
      column_types:
        PROJECT_NAME: VARCHAR2(255)
        CURRENT_COB_DATE: DATE
        LAST_COB_DATE: DATE
        IS_INIT: INT
