version: 2

seeds:
  - name: DIM_COREBANK_KDI
    config:
      column_types:
        COB_DATE: DATE
        BRN_CODE: VARCHAR(255)
        KDI1: VARCHAR(255)
        KDI2: VARCHAR(255)
        KDI3: VARCHAR(255)
        KDI4: VARCHAR(255)
        KDI5: VARCHAR(255)
        KDI6: VARCHAR(255)
        KDI7: DATE
        KDI8: VARCHAR(255)
        KDI9: VARCHAR(255)
        KDI10: VARCHAR(255)
        KDI10_01: VARCHAR(255)
        KDI10_02: VARCHAR(255)
        KDI10_03: VARCHAR(255)
        KDI10_04: VARCHAR(255)
        KDI10_05: VARCHAR(255)
        KDI10_06: VARCHAR(255)
        KDI11: VARCHAR(255)
        KDI11_01: VARCHAR(255)
        KDI11_02: VARCHAR(255)
        KDI11_03: VARCHAR(255)
        KDI11_04: VARCHAR(255)
        KDI11_05: VARCHAR(255)
        KDI11_06: VARCHAR(255)
        KDI12: VARCHAR(255)
        KDI12_01: VARCHAR(255)
        KDI12_02: VARCHAR(255)
        KDI12_03: VARCHAR(255)
        KDI12_04: VARCHAR(255)
        KDI12_05: VARCHAR(255)
        KDI12_06: VARCHAR(255)
        KDI13: VARCHAR(255)
        KDI13_01: VARCHAR(255)
        KDI13_02: VARCHAR(255)
        KDI13_03: VARCHAR(255)
        KDI13_04: VARCHAR(255)
        KDI13_05: VARCHAR(255)
        KDI13_06: VARCHAR(255)
        KDI14: VARCHAR(255)
        KDI14_01: VARCHAR(255)
        KDI14_02: VARCHAR(255)
        KDI14_03: VARCHAR(255)
        KDI14_04: VARCHAR(255)
        KDI14_05: VARCHAR(255)
        KDI14_06: VARCHAR(255)
        KDI15: VARCHAR(255)
        KDI16: VARCHAR(255)
        KDI17: VARCHAR(255)
        KDI18: VARCHAR(255)
        KDI19: VARCHAR(255)
        KDI20: VARCHAR(255)
        KDI21_01: VARCHAR(255)
        KDI21_02: DATE
        KDI21_03: VARCHAR(255)
        KDI22_01: VARCHAR(255)
        KDI22_02: DATE
        KDI22_03: VARCHAR(255)
        KDI23_01: VARCHAR(255)
        KDI23_02: DATE
        KDI23_03: VARCHAR(255)
        KDI23_04: VARCHAR(255)
        KDI24_01: VARCHAR(255)
        KDI24_02: VARCHAR(255)
        KDI24_03: VARCHAR(255)
        KDI25_01: VARCHAR(255)
        KDI25_02: VARCHAR(255)
        KDI25_03: VARCHAR(255)
        KDI26_01: VARCHAR(255)
        KDI26_02: VARCHAR(255)
        KDI26_03: VARCHAR(255)
        KDI27_01: VARCHAR(255)
        KDI27_02: VARCHAR(255)
        KDI27_03: VARCHAR(255)
        KDI28_01: VARCHAR(255)
        KDI28_02: VARCHAR(255)
        KDI28_03: VARCHAR(255)
        KDI29_01: VARCHAR(255)
        KDI29_02: VARCHAR(255)
        KDI29_03: VARCHAR(255)
        KDI30_01: VARCHAR(255)
        KDI30_02: VARCHAR(255)
        KDI30_03: VARCHAR(255)
        KDI30_04: VARCHAR(255)
        KDI31: VARCHAR(255)
        KDI32: VARCHAR(255)
        KDI33_01: VARCHAR(255)
        KDI33_02: VARCHAR(255)
        KDI33_03: VARCHAR(255)
        KDI33_04: VARCHAR(255)
        KDI34_01: VARCHAR(255)
        KDI34_02: VARCHAR(255)
        KDI34_03: VARCHAR(255)
        KDI34_04: VARCHAR(255)
        KDI34_05: VARCHAR(255)
        KDI35: VARCHAR(255)
        KDI36: VARCHAR(255)
        KDI37: VARCHAR(255)
        KDI38: VARCHAR(255)
        KDI39: VARCHAR(255)
        KDI40: VARCHAR(255)
        KDI41: VARCHAR(255)
        KDI42: VARCHAR(255)
        KDI43: VARCHAR(255)
        KDI44: VARCHAR(255)
        KDI45: VARCHAR(255)
        KDI46: VARCHAR(255)
        KDI47: VARCHAR(255)
        KDI48: VARCHAR(255)
        KDI49: VARCHAR(255)
        KDI50: VARCHAR(255)
        KDI51: VARCHAR(255)
        KDI52: DATE
        KDI53: VARCHAR(255)
        KDI54: VARCHAR(255)
        KDI55: VARCHAR(255)
        KDI2_CDT: TIMESTAMP
        KDI3_CDT: TIMESTAMP
        KDI4_CDT: TIMESTAMP
        KDI5_CDT: TIMESTAMP
        KDI6_CDT: TIMESTAMP
        KDI7_CDT: TIMESTAMP
        KDI8_CDT: TIMESTAMP
        KDI9_CDT: TIMESTAMP
        KDI10_CDT: TIMESTAMP
        KDI10_01_CDT: TIMESTAMP
        KDI10_02_CDT: TIMESTAMP
        KDI10_03_CDT: TIMESTAMP
        KDI10_04_CDT: TIMESTAMP
        KDI10_05_CDT: TIMESTAMP
        KDI10_06_CDT: TIMESTAMP
        KDI11_CDT: TIMESTAMP
        KDI11_01_CDT: TIMESTAMP
        KDI11_02_CDT: TIMESTAMP
        KDI11_03_CDT: TIMESTAMP
        KDI11_04_CDT: TIMESTAMP
        KDI11_05_CDT: TIMESTAMP
        KDI11_06_CDT: TIMESTAMP
        KDI12_CDT: TIMESTAMP
        KDI12_01_CDT: TIMESTAMP
        KDI12_02_CDT: TIMESTAMP
        KDI12_03_CDT: TIMESTAMP
        KDI12_04_CDT: TIMESTAMP
        KDI12_05_CDT: TIMESTAMP
        KDI12_06_CDT: TIMESTAMP
        KDI13_CDT: TIMESTAMP
        KDI13_01_CDT: TIMESTAMP
        KDI13_02_CDT: TIMESTAMP
        KDI13_03_CDT: TIMESTAMP
        KDI13_04_CDT: TIMESTAMP
        KDI13_05_CDT: TIMESTAMP
        KDI13_06_CDT: TIMESTAMP
        KDI14_CDT: TIMESTAMP
        KDI14_01_CDT: TIMESTAMP
        KDI14_02_CDT: TIMESTAMP
        KDI14_03_CDT: TIMESTAMP
        KDI14_04_CDT: TIMESTAMP
        KDI14_05_CDT: TIMESTAMP
        KDI14_06_CDT: TIMESTAMP
        KDI15_CDT: TIMESTAMP
        KDI16_CDT: TIMESTAMP
        KDI17_CDT: TIMESTAMP
        KDI18_CDT: TIMESTAMP
        KDI19_CDT: TIMESTAMP
        KDI20_CDT: TIMESTAMP
        KDI21_01_CDT: TIMESTAMP
        KDI21_02_CDT: TIMESTAMP
        KDI21_03_CDT: TIMESTAMP
        KDI22_01_CDT: TIMESTAMP
        KDI22_02_CDT: TIMESTAMP
        KDI22_03_CDT: TIMESTAMP
        KDI23_01_CDT: TIMESTAMP
        KDI23_02_CDT: TIMESTAMP
        KDI23_03_CDT: TIMESTAMP
        KDI23_04_CDT: TIMESTAMP
        KDI24_01_CDT: TIMESTAMP
        KDI24_02_CDT: TIMESTAMP
        KDI24_03_CDT: TIMESTAMP
        KDI25_01_CDT: TIMESTAMP
        KDI25_02_CDT: TIMESTAMP
        KDI25_03_CDT: TIMESTAMP
        KDI26_01_CDT: TIMESTAMP
        KDI26_02_CDT: TIMESTAMP
        KDI26_03_CDT: TIMESTAMP
        KDI27_01_CDT: TIMESTAMP
        KDI27_02_CDT: TIMESTAMP
        KDI27_03_CDT: TIMESTAMP
        KDI28_01_CDT: TIMESTAMP
        KDI28_02_CDT: TIMESTAMP
        KDI28_03_CDT: TIMESTAMP
        KDI29_01_CDT: TIMESTAMP
        KDI29_02_CDT: TIMESTAMP
        KDI29_03_CDT: TIMESTAMP
        KDI30_01_CDT: TIMESTAMP
        KDI30_02_CDT: TIMESTAMP
        KDI30_03_CDT: TIMESTAMP
        KDI30_04_CDT: TIMESTAMP
        KDI31_CDT: TIMESTAMP
        KDI32_CDT: TIMESTAMP
        KDI33_01_CDT: TIMESTAMP
        KDI33_02_CDT: TIMESTAMP
        KDI33_03_CDT: TIMESTAMP
        KDI33_04_CDT: TIMESTAMP
        KDI34_01_CDT: TIMESTAMP
        KDI34_02_CDT: TIMESTAMP
        KDI34_03_CDT: TIMESTAMP
        KDI34_04_CDT: TIMESTAMP
        KDI34_05_CDT: TIMESTAMP
        KDI35_CDT: TIMESTAMP
        KDI36_CDT: TIMESTAMP
        KDI37_CDT: TIMESTAMP
        KDI38_CDT: TIMESTAMP
        KDI39_CDT: TIMESTAMP
        KDI40_CDT: TIMESTAMP
        KDI41_CDT: TIMESTAMP
        KDI42_CDT: TIMESTAMP
        KDI43_CDT: TIMESTAMP
        KDI44_CDT: TIMESTAMP
        KDI45_CDT: TIMESTAMP
        KDI46_CDT: TIMESTAMP
        KDI47_CDT: TIMESTAMP
        KDI48_CDT: TIMESTAMP
        KDI49_CDT: TIMESTAMP
        KDI50_CDT: TIMESTAMP
        KDI51_CDT: TIMESTAMP
        KDI52_CDT: TIMESTAMP
        KDI53_CDT: TIMESTAMP
        KDI54_CDT: TIMESTAMP
        KDI55_CDT: TIMESTAMP